#!/bin/bash

gsc-script -track-scheme 
sclos.scm
remodel.scm
support-lib.scm
utils.scm
units.scm
sort.scm
maths.scm
integrate.scm
matrix.scm

postscript.scm
basic-population.scm
remodel-controls.scm
remodel-classes.scm
remodel-declarations.scm

remodel-methods.scm
log.scm
log-classes.scm
log-declarations.scm
log-methods.scm
landscape.scm
landscape-classes.scm

landscape-declarations.scm
landscape-methods.scm
animal.scm
animal-classes.scm
animal-declarations.scm
animal-methods.scm

kernel.scm
model-configuration.scm


